<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ReaperLeaderboardPlugin</AssemblyName>
    <RootNamespace>ReaperLeaderboardPlugin</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Rocket.API">
      <HintPath>..\..\Libs\Rocket.API.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Rocket.Core">
      <HintPath>..\..\Libs\Rocket.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Rocket.Unturned">
      <HintPath>..\..\Libs\Rocket.Unturned.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\Libs\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\Libs\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\..\Libs\com.rlabrecque.steamworks.net.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MySql.Data">
      <HintPath>..\..\Libs\MySql.Data.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
